name: Codespace
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: make install
    - name: lint
      run: pylint --disable=R,C hello.py
    - name: test
      run: python -m pytest -vv --cov=hello test_hello.py
    - name: format
      run: black *.py

